import { CustomerTrainingForm } from '../types/customerTraining';

export function generateTrackingNo(): string {
  const year = new Date().getFullYear();
  const randomNum = Math.floor(100 + Math.random() * 900);
  return `TIF-${year}-${randomNum}`;
}

export const initialFormValues: CustomerTrainingForm = {
  distribution: {
    sendTo: ['Operation', 'Training'],
    customerStatus: 'Fulltime',
  },
  customer: {
    fullName: '',
    nickname: '',
    trackingNo: generateTrackingNo(),
    customerType: 'Individual',
    corporateName: '',
    agencyName: '',
    joiningBatch: 'Batch 2026/01',
    dateOfBirth: '',
    idPassportNo: '',
    email: '',
    phone: '',
    lineWechat: '',
    nationality: 'Thai',
    address: '',
  },
  emergencyContact: {
    name: '',
    relationship: '',
    phone: '',
    email: '',
    address: '',
    additionalContact: '',
  },
  licenseMedical: {
    currentLicense: 'Student',
    otherLicense: '',
    ratingsHeld: [],
    otherRating: '',
    totalFlightTime: 0,
    medical: 'Class 1',
    issuingAuthority: 'CAAT (Civil Aviation Authority of Thailand)',
    expiry: '',
    underlyingDiseaseRemarks: 'None',
    drugAllergy: 'None',
    foodAllergy: 'None',
  },
  courseOrder: {
    courses: ['CPL/IR Integrated + ATP'],
    otherCourse: '',
    aircraftType: 'Cessna 172SP / Diamond DA42',
    package: 'Full Integrated Commercial Pilot Course',
    preferredStart: new Date().toISOString().slice(0, 10),
    estimatedDuration: '14 Months',
    trainingComponents: ['Ground', 'Flight', 'Simulator', 'CAAT Exam', 'Skill Test', 'ICAO ELP'],
    specialRequirements: '',
  },
  otherServices: {
    accommodation: 'Included',
    meals: 'Not Included',
    transportation: 'Included',
    visaFee: 'Not Included',
    examFee: 'Included',
    otherSupport: 'Provide pilot uniforms, flight bag, headset, and navigation study materials.',
  },
  finance: {
    totalPrice: 2850000,
    discount: 50000,
    finalPrice: 2800000,
    depositRequired: 'Yes',
    depositDate: new Date().toISOString().slice(0, 10),
    depositReceived: 100000,
    paymentMethod: ['Transfer'],
    installmentDetails: 'Deposit 100,000 THB upon signing. Balance divided into 4 milestones.',
    corporateBalance: 0,
    documents: ['ID copy', 'Medical', 'Photos'],
    otherDocument: '',
    eligibilityVerified: 'Yes',
    eligibilityRemarks: 'Passed academic background check and pre-medical screening.',
    remarks: 'Standard student agreement terms apply. Student must adhere to flight safety guidelines and attendance regulations.',
  },
  approval: {
    approvedBy: 'Capt. Somchai Prasert (Sales Director)',
    approvalDate: new Date().toISOString().slice(0, 10),
    salesOfficer: 'Napasorn Wongsuwan',
    salesOfficerDate: new Date().toISOString().slice(0, 10),
    signature: '',
  },
};

export const sampleCompletedFormValues: CustomerTrainingForm = {
  distribution: {
    sendTo: ['Operation', 'Finance', 'Training', 'Standard/Compliance'],
    customerStatus: 'Fulltime',
  },
  customer: {
    fullName: 'Thanaphat Wongsuwan',
    nickname: 'Pat',
    trackingNo: 'TIF-2026-088',
    customerType: 'Individual',
    corporateName: '',
    agencyName: '',
    joiningBatch: 'Batch 2026/02',
    dateOfBirth: '2001-05-14',
    idPassportNo: '1100500987654',
    email: 'thanaphat.pat@gmail.com',
    phone: '089-123-4567',
    lineWechat: 'pat_pilot26',
    nationality: 'Thai',
    address: '88/12 Sukhumvit 71 Road, Phra Khanong Nuea, Watthana, Bangkok 10110',
  },
  emergencyContact: {
    name: 'Somchai Wongsuwan',
    relationship: 'Father',
    phone: '081-987-6543',
    email: 'somchai.w@gmail.com',
    address: '88/12 Sukhumvit 71 Road, Phra Khanong Nuea, Watthana, Bangkok 10110',
    additionalContact: 'Mother: Khun Suree (082-555-4433)',
  },
  licenseMedical: {
    currentLicense: 'Student',
    otherLicense: '',
    ratingsHeld: ['SEP'],
    otherRating: '',
    totalFlightTime: 25,
    medical: 'Class 1',
    issuingAuthority: 'Civil Aviation Authority of Thailand (CAAT)',
    expiry: '2027-04-30',
    underlyingDiseaseRemarks: 'None / Fit to fly',
    drugAllergy: 'No known drug allergies',
    foodAllergy: 'Peanut allergy (mild)',
  },
  courseOrder: {
    courses: ['CPL/IR Integrated + ATP'],
    otherCourse: '',
    aircraftType: 'Cessna 172SP Skyhawk & Diamond DA42-VI',
    package: 'Professional Airline Pilot Program 2026',
    preferredStart: '2026-11-01',
    estimatedDuration: '14 Months',
    trainingComponents: ['Ground', 'Flight', 'Simulator', 'CAAT Exam', 'Skill Test', 'ICAO ELP'],
    specialRequirements: 'Request simulator schedule on weekday mornings.',
  },
  otherServices: {
    accommodation: 'Included',
    meals: 'Included',
    transportation: 'Included',
    visaFee: 'Not Included',
    examFee: 'Included',
    otherSupport: 'Student kit, aviation iPad holder, uniform set (3 sets), and logbook included.',
  },
  finance: {
    totalPrice: 2850000,
    discount: 50000,
    finalPrice: 2800000,
    depositRequired: 'Yes',
    depositDate: '2026-10-15',
    depositReceived: 150000,
    paymentMethod: ['Transfer', 'Installments'],
    installmentDetails: 'Payment schedule: 150,000 THB deposit, 4 quarterly installments of 662,500 THB.',
    corporateBalance: 0,
    documents: ['ID copy', 'Medical', 'License copy', 'Photos', 'English/ELP'],
    otherDocument: 'Graduation Certificate',
    eligibilityVerified: 'Yes',
    eligibilityRemarks: 'Academic transcript and CAAT Class 1 Medical certified.',
    remarks: 'Candidate successfully passed the pre-assessment interview and English aviation screening.',
  },
  approval: {
    approvedBy: 'Capt. Voravit Rungreang (Sales Director)',
    approvalDate: '2026-10-10',
    salesOfficer: 'Pannika Chaisri (Senior Sales Executive)',
    salesOfficerDate: '2026-10-10',
    signature: '',
  },
};
